name: Metrics
on:
  # Chạy tự động mỗi ngày lúc 0h
  schedule: [{cron: "0 0 * * *"}]
  # Cho phép chạy thủ công
  workflow_dispatch:
  # Chạy mỗi khi push vào main
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token mặc định của GitHub
          token: ${{ secrets.GITHUB_TOKEN }}

          # Cấu hình user
          user: GianT404
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh

          # Kích hoạt chế độ Isometric (Thành phố 3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
